import sqlite3
from sqlite3 import Error

def create_table(con, query):
    cur = con.cursor()
    cur.execute(query)
def createDB(db_file, schema_file):
    try:
        con = sqlite3.connect(db_file)

        with open(schema_file) as f:
            con.executescript(f.read())

        # insert issues into table
        sql_stdteams = """INSERT INTO teams(id, color) VALUES (0, "red"), (1, "blue"), (2, "yellow");"""
        sql_stduser = """INSERT INTO users(name, team_id) VALUES ("tom", 0), ("jana", 1), ("fabian", 2), ("arthur", 0);"""
        sql_insert_std_issues = """INSERT INTO splatzones(pos_long, pos_lat, osm_id) VALUES
                                                (11.61430161647961,48.111355593621,154359841),
                                                (11.606248275586244,48.17566584451249,38690109),
                                                (11.63329945842623,48.13569262741428,460354029),
                                                (11.58813361092573,48.1765304782419,259583217),
                                                (11.570784175202212,48.14912076050485,122159109),
                                                (11.60678544203654,48.17607553069282,38690109),
                                                (11.5806306,48.106241100000005,362796882),
                                                (11.613351477617488,48.13046701048668,122002285),
                                                (11.622674470519335,48.16163430223077,38926857),
                                                (11.608645678780396,48.172420882348,99663070),
                                                (11.547805204701106,48.11291668736461,173096616),
                                                (11.6237920164228,48.16265466072837,100945239),
                                                (11.61900312193212,48.118031503459626,49915865),
                                                (11.60673962645799,48.17604819685549,38690109),
                                                (11.62046123985182,48.12177302648248,292781203),
                                                (11.615932367309346,48.11290549141834,32256065),
                                                (11.61818097587384,48.11925483880852,27334574),
                                                (11.616833182061308,48.16881681797188,38123963),
                                                (11.5873091,48.104692400000005,40108148),
                                                (11.603695515414293,48.17208671297508,38690109),
                                                (11.615292419261202,48.11211300211448,37666015),
                                                (11.525206316022905,48.14868644684231,54200279),
                                                (11.601411486290576,48.171796512604,159686837),
                                                (11.549527023953246,48.16089514763812,90165750),
                                                (11.618987385257748,48.11835266871433,230251455),
                                                (11.624135105357796,48.16302274431093,467655365),
                                                (11.541217267708962,48.10089803370931,262486709),
                                                (11.617648147817643,48.11503273780353,311181487),
                                                (11.613106928911195,48.17299008497127,37208105),
                                                (11.527965543942017,48.14774795111176,54200280);
                                    """
        cur = con.cursor()
        cur.execute(sql_stdteams)
        cur.execute(sql_stduser)
        cur.execute(sql_insert_std_issues)
        con.commit()
        con.close()

    except Error as e:
        print(e)

if __name__ == "__main__":
    DB_FILE = "paint.db"
    SCHEMA_FILE = "schema.sql"
    createDB(DB_FILE, SCHEMA_FILE)
